config/routes.rb
Barker::Application.routes.draw do

  resources :users do
    collection do
      get 'login', 'logout'
      post 'process_login'
    end
  end

  resources :barks
  match 'timelines/:id' => 'timelines#show', :as => :timeline, :via => :get

  root :to => "barks#index"

end

app/models/bark.rb
class Bark < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :barks

  def self.authenticate(user_info)
    find_by_name_and_password(user_info[:name], user_info[:password])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/barks_controller.rb
class BarksController < ApplicationController

  def index
    @barks = Bark.all

  end

  def new
    @bark = Bark.new

  end

  def create
    @bark = Bark.new(params[:bark])
    if session[:id]
      @bark.user_id = session[:id]
    end

    respond_to do |format|
      if @bark.save
        format.html { redirect_to(timeline_path session[:id]) }
      else
        format.xml { render :action => "new" }
      end
    end

  end

end

app/controllers/timelines_controller.rb
class TimelinesController < ApplicationController

  def show
    @user_id = params[:id]
    if @user_id
      @barks = Bark.find_all_by_user_id(@user_id)
    end

    respond_to do |format|
      format.html
      format.xml  { render :xml => @barks }
    end

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index 
    @users = User.all 

  end

  def new
    @user = User.new
    puts 'I am at action "new"!'

  end

  def create
    @user = User.new(params[:user])
    @user.created_date = Time.now

    respond_to do |format|
      if @user.save
        format.html { redirect_to(users_path, :notice => 'User was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  
  end

  def login
    @user = User.new

  end

  def process_login

    respond_to do |format|
      if user = User.authenticate(params[:user])
        session[:id] = user.id
        format.html { redirect_to(barks_path) }
      else
        format.html { redirect_to(login_users_path, :notice => 'Invalid login.') }
      end
    end

  end

  def logout
    reset_session

    respond_to do |format|
      format.html { redirect_to(login_users_path, :notice => 'Logged out.') }
    end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/barks_helper.rb
module BarksHelper
end

app/helpers/timelines_helper.rb
module TimelinesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/barks/_form.html.erb
<%= form_for(@bark) do |f| %>                                                                                                                               
  <div class="field">
    <%= f.text_area :status, :size => "70x2" %>
  </div>
  <div class="actions">
    <%= f.submit 'Bark!' %>
  </div>
<% end %>

app/views/barks/index.html.erb
<h1>Listing Barks</h1>

<% if session[:id] %>
  <h2>
    <font color="green">Welcome, <%= User.find(session[:id]).fullname %>!</font>
    <%= link_to '(logout)', logout_users_path %>
  </h2>
<% else %>
  <h2>
    <font color="green">Please <%= link_to 'Sign Up', new_user_path %> to share your bark!</font>
  </h2>
  <h3>
    Aready have an accout? Please <%= link_to 'Log In', login_users_path %>.</font>
  </h3>
<% end %>

<table border="1">
  <tr>
    <th>Username</th>
    <th>Status</th>
  </tr>

  <% @barks.each do |bark| %>
    <tr>
      <td><%= bark.user.name %></td>
      <td><%= bark.status %></td>
    </tr>
  <% end %>
</table>

<br />

<% if session[:id] %>
  <%= link_to 'Send a new bark', new_bark_path %>
<% end %>

app/views/barks/new.html.erb
<h1>What's happening?</h1>

<p></p>

<%= render 'form' %>

<%= link_to 'Back to bark list', '/' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barker</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/timelines/show.html.erb
<h1>Timeline</h1>

<% if session[:id] %>
  <h2>
    <font color="green"><%= User.find(@user_id).fullname %>'s barks</font>
    <%= link_to '(logout)', logout_users_path %>
  </h2>
<% else %>
  <h2>
    <font color="green">Please <%= link_to 'Sign Up', new_user_path %> to share your bark!</font>
  </h2>
  <h3>
    Aready have an accout? Please <%= link_to 'Log In', logout_users_path %>.</font>
  </h3>
<% end %>

<table border="1">
  <tr>
    <th>Status</th>
    <th>Date</th>
  </tr>

  <% @barks.each do |bark| %>
    <tr>
      <td><%= bark.status %></td>
      <td><%= bark.created_at %></td>
    </tr>
  <% end %>
</table>

<br />

<% if session[:id] %>
  <%= link_to 'Send a new bark', new_bark_path %>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>                                                                                                                               

  <div class="field">
    <%= f.label :name, 'Username:' %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email, 'Email:' %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :fullname, 'Full name:' %><br />
    <%= f.text_field :fullname %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password:' %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign up' %>
  </div>
<% end %>

app/views/users/_form_login.html.erb
<%= form_for(@user, :url => { :action => "process_login" }) do |f| %>                                                                                                                               

  <div class="field">
    <%= f.label :name, 'Username:' %><br />
    <%= f.text_field :name  %>
  </div>
  <div class="field">
    <%= f.label :password, 'Password:' %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Sign in' %>
  </div>
<% end %>

app/views/users/index.html.erb
<p id="notice"><font color="red"><%= notice %></font></p>

<%= link_to 'Register new user', new_user_path %>

app/views/users/login.html.erb
<h1>Login</h1>

<p id="notice"><font color="red"><%= notice %></font></p>
<p id="alert"><font color="red"><%= alert %></font></p>

<%= render 'form_login' %>

<%= link_to 'Back to bark list', '/' %>

app/views/users/new.html.erb
<h1>Registration</h1>

<%= render 'form' %>

<%= link_to 'Back to bark list', '/' %>

app/views/users/process_login.html.erb
<h1>Login Successfully</h1>